### ISSUE TITLE
运行发现openid未定义与functions文件夹里的js、json文件无法打包上传问题

### ISSUE THREAD

**Issue by pacomusume** [Wayne-Mai/WeChat-MiniProgram-2019#1]
您好，我是代码小白，用微信开发工具运行您的小程序出现下面2个问题，想请问一下要怎么解决，一是：
`VM331:1 thirdScriptError
Cannot read property 'openid' of undefined;at pages/helper/index onLoad function;at api cloud.callFunction complete callback function
TypeError: Cannot read property 'openid' of undefined
    at Function.complete (http://127.0.0.1:32418/appservice/pages/helper/index.js:33:93)
    at Function.<anonymous> (WAService.js:1:102353)
    at WAService.js:1:382452
    at a (WAService.js:1:382161)
    at WAService.js:1:382430
    at s (WAService.js:1:258748)
    at Object.t.invokeFailCompleteCallbacks (WAService.js:1:258951)
    at WAService.js:1:352107
`
二是functions文件夹里的js、json文件都无法上传，我的工作环境是win10，32位，云开发免费版，小程序我不发布，就是用在公司群里，15人的体验版够用了。可以的话麻烦给我一个解决方法，谢谢。
![群通知](https://user-images.githubusercontent.com/53211352/61691385-02fa4d00-ad5e-11e9-91cf-a86d56f97dde.png)

**Comment by Wayne-Mai** [comment]
getOpenId是我定义的云函数, 也是基于微信提供的云平台. 虽然我已经提供了代码(在function文件夹), 但你仍需要自己完成一下相关配置, 可以参照微信官方文档, 注意同步云函数等.

**Comment by Wayne-Mai** [comment]
https://developers.weixin.qq.com/miniprogram/dev/wxcloud/guide/functions/getting-started.html
你只需要把对应的index.js换成对应的函数代码就好了
